services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
    restart: always
    environment:
      - MONGO_INIT_ROOT_USERNAME=admin
      - MONGO_INIT_ROOT_PASSWORD=admin
